[package]
name = "wasm-percolator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"


[profile.release]
lto=true
opt-level = 's'
